server:
  port: 8081
  
spring:
  application:
    name: API_GATEWAY
    
    
  cloud:
    gateway:
      routes:
      - id: TRAVEL
        uri:
          lb://TRAVEL
        predicates:
        - Path=/travel/**
        